# Generated by Django 2.1.5 on 2019-02-05 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_follower_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='follower_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='followed_by',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
